name: deploy
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.1"

      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra/terraform
        run: terraform plan -no-color

      - name: Terraform Apply
        working-directory: ./infra/terraform
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: terraform-outputs
        working-directory: ./infra/terraform
        run: |
          echo "s3_bucket_name=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_OUTPUT
          echo "cloudfront_domain_name=$(terraform output -raw cloudfront_domain_name)" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Build application
        run: pnpm -w build

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ steps.terraform-outputs.outputs.s3_bucket_name }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ steps.terraform-outputs.outputs.cloudfront_distribution_id }}
          CLOUDFRONT_DOMAIN_NAME: ${{ steps.terraform-outputs.outputs.cloudfront_domain_name }}
          AWS_REGION: us-east-1
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
